# Generated by Django 4.2.15 on 2024-12-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_article_generation', models.BooleanField(default=False)),
                ('llm_tags_generation', models.BooleanField(default=False)),
            ],
        ),
    ]
